-- ============================================================================
-- Pharmacy2U Demo - RBAC and Permissions Setup
-- Purpose: Configure role-based access control for demo scenarios
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- Create Demo Roles
-- ============================================================================

-- Data Engineer role (full access to all layers)
CREATE ROLE IF NOT EXISTS PHARMACY2U_DATA_ENGINEER;
GRANT ROLE PHARMACY2U_DATA_ENGINEER TO ROLE ACCOUNTADMIN;

-- Data Analyst role (read access to GOLD layer)
CREATE ROLE IF NOT EXISTS PHARMACY2U_DATA_ANALYST;
GRANT ROLE PHARMACY2U_DATA_ANALYST TO ROLE ACCOUNTADMIN;

-- BI User role (limited access with masking)
CREATE ROLE IF NOT EXISTS PHARMACY2U_BI_USER;
GRANT ROLE PHARMACY2U_BI_USER TO ROLE ACCOUNTADMIN;

-- Data Scientist role (read GOLD, write ML models)
CREATE ROLE IF NOT EXISTS PHARMACY2U_DATA_SCIENTIST;
GRANT ROLE PHARMACY2U_DATA_SCIENTIST TO ROLE ACCOUNTADMIN;

-- ============================================================================
-- Grant Warehouse Permissions
-- ============================================================================

-- Data Engineer - all warehouses
GRANT USAGE ON WAREHOUSE PHARMACY2U_DEMO_WH TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE PHARMACY2U_LOADING_WH TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE PHARMACY2U_ML_WH TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE PHARMACY2U_ANALYTICS_WH TO ROLE PHARMACY2U_DATA_ENGINEER;

-- Data Analyst - demo and analytics warehouses only
GRANT USAGE ON WAREHOUSE PHARMACY2U_DEMO_WH TO ROLE PHARMACY2U_DATA_ANALYST;
GRANT USAGE ON WAREHOUSE PHARMACY2U_ANALYTICS_WH TO ROLE PHARMACY2U_DATA_ANALYST;

-- BI User - analytics warehouse only
GRANT USAGE ON WAREHOUSE PHARMACY2U_ANALYTICS_WH TO ROLE PHARMACY2U_BI_USER;

-- Data Scientist - demo and ML warehouses
GRANT USAGE ON WAREHOUSE PHARMACY2U_DEMO_WH TO ROLE PHARMACY2U_DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE PHARMACY2U_ML_WH TO ROLE PHARMACY2U_DATA_SCIENTIST;

-- ============================================================================
-- Grant Database and Schema Permissions
-- ============================================================================

-- Data Engineer - full access to all databases
GRANT USAGE ON DATABASE PHARMACY2U_BRONZE TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON DATABASE PHARMACY2U_SILVER TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON DATABASE PHARMACY2U_GOLD TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON DATABASE PHARMACY2U_DEMO_DB TO ROLE PHARMACY2U_DATA_ENGINEER;

GRANT USAGE ON ALL SCHEMAS IN DATABASE PHARMACY2U_BRONZE TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PHARMACY2U_SILVER TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PHARMACY2U_GOLD TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PHARMACY2U_DEMO_DB TO ROLE PHARMACY2U_DATA_ENGINEER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PHARMACY2U_BRONZE.RAW_DATA TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PHARMACY2U_SILVER.GOVERNED_DATA TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_DATA_ENGINEER;

-- Data Analyst - read access to GOLD layer
GRANT USAGE ON DATABASE PHARMACY2U_GOLD TO ROLE PHARMACY2U_DATA_ANALYST;
GRANT USAGE ON DATABASE PHARMACY2U_DEMO_DB TO ROLE PHARMACY2U_DATA_ANALYST;
GRANT USAGE ON SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_DATA_ANALYST;

-- BI User - limited read access to GOLD layer with masking
GRANT USAGE ON DATABASE PHARMACY2U_GOLD TO ROLE PHARMACY2U_BI_USER;
GRANT USAGE ON SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_BI_USER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_BI_USER;

-- Data Scientist - read GOLD, write models
GRANT USAGE ON DATABASE PHARMACY2U_GOLD TO ROLE PHARMACY2U_DATA_SCIENTIST;
GRANT USAGE ON DATABASE PHARMACY2U_DEMO_DB TO ROLE PHARMACY2U_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_DATA_SCIENTIST;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_DATA_SCIENTIST;

-- ============================================================================
-- Future Grants (for objects created later)
-- ============================================================================

-- Data Engineer future grants
GRANT ALL ON FUTURE TABLES IN SCHEMA PHARMACY2U_BRONZE.RAW_DATA TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PHARMACY2U_SILVER.GOVERNED_DATA TO ROLE PHARMACY2U_DATA_ENGINEER;
GRANT ALL ON FUTURE VIEWS IN SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_DATA_ENGINEER;

-- Data Analyst future grants
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_DATA_ANALYST;

-- BI User future grants
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_BI_USER;

-- Data Scientist future grants
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY2U_GOLD.ANALYTICS TO ROLE PHARMACY2U_DATA_SCIENTIST;

SELECT 
    'RBAC configuration completed successfully' AS STATUS,
    '4 roles created: DATA_ENGINEER, DATA_ANALYST, BI_USER, DATA_SCIENTIST' AS ROLES_CREATED;
